In [1]:
# 引入包
import torch
import torchvision
import numpy as np
import torch.nn as nn 
import torch.nn.functional as F
from torch.utils.data import Dataset
from torch.utils.data.dataloader import DataLoader

In [3]:
# Tensor（张量），NumPy 的 ndarray ，但还可以在 GPU 上使用来加速计算
# 创建一个没有初始化的 5 * 3 矩阵：
x=torch.empty(5,3)
print(x)

tensor([[ 4.4879e-05,  4.5848e-41, -2.3110e+08],
        [ 3.0949e-41,  8.0519e-42,  3.6265e-38],
        [ 7.6362e-28,  2.5353e+30,  4.5682e-43],
        [ 6.2582e-42,  2.5205e-39,  7.8194e-25],
        [ 2.5353e+30,  5.2268e-43,  4.1058e-42]])


In [4]:
# 创建随机初始化矩阵
x=torch.rand(5,3)
print(x)

tensor([[0.5024, 0.8874, 0.1422],
        [0.8737, 0.0718, 0.2871],
        [0.4131, 0.9910, 0.6148],
        [0.5146, 0.8731, 0.3427],
        [0.1783, 0.1809, 0.3206]])


In [6]:
# 构造一个填满 0 且数据类型为 long 的矩阵
x=torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [7]:
# 从数据构造张量
x=torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [11]:
# 根据现有的 tensor 建立新的 tensor 。
# 除非用户提供新的值，否则这些方法将重用输入张量的属性，例如 dtype 等：
x=x.new_ones(5,3,dtype=torch.double)
print(x)
x= torch.randn_like(x,dtype=torch.float)
print(x)
# 获取张量形状
print(x.size())

# 运算
# 加法1
y=torch.rand(5,3)
print(x+y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.3899,  1.4075,  0.4371],
        [-0.7676, -1.3429, -0.7746],
        [ 1.1455, -0.1640, -0.2900],
        [-1.2693,  0.6132,  1.5849],
        [-0.3962,  0.0232,  0.9026]])
torch.Size([5, 3])
tensor([[ 0.9015,  1.4626,  1.4232],
        [-0.7093, -0.6240, -0.5052],
        [ 1.7322,  0.2324, -0.2443],
        [-0.9972,  1.2347,  1.5986],
        [ 0.5572,  0.0422,  1.7399]])


In [12]:
# 根据现有的 tensor 建立新的 tensor 。
# 除非用户提供新的值，否则这些方法将重用输入张量的属性，例如 dtype 等：
x=x.new_ones(5,3,dtype=torch.double)
print(x)
x= torch.randn_like(x,dtype=torch.float)
print(x)

# 运算
# 加法1
y=torch.rand(5,3)
print(x+y)

# 加法2
print(torch.add(x,y))

# 给定一个输出张量作为参数
result=torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.7336, -2.9922, -0.7091],
        [-0.4069,  0.0747, -0.8170],
        [-0.1389, -0.6014, -0.5661],
        [ 0.5452,  2.0737,  0.4815],
        [-0.3291, -1.2178, -0.8690]])
tensor([[ 0.1003, -2.2846, -0.4287],
        [-0.1647,  0.4394,  0.0040],
        [ 0.5186, -0.4379, -0.2009],
        [ 0.9509,  2.3721,  0.8443],
        [ 0.6170, -0.3416,  0.0879]])
tensor([[ 0.1003, -2.2846, -0.4287],
        [-0.1647,  0.4394,  0.0040],
        [ 0.5186, -0.4379, -0.2009],
        [ 0.9509,  2.3721,  0.8443],
        [ 0.6170, -0.3416,  0.0879]])
tensor([[ 0.1003, -2.2846, -0.4287],
        [-0.1647,  0.4394,  0.0040],
        [ 0.5186, -0.4379, -0.2009],
        [ 0.9509,  2.3721,  0.8443],
        [ 0.6170, -0.3416,  0.0879]])


In [14]:
# 就地操作
# 任何一个就地改变张量的操作后面都固定一个 _ 。例如 x.copy_（y）， x.t_（）将更改x
y.add_(x)
print(y)

tensor([[ 0.1003, -2.2846, -0.4287],
        [-0.1647,  0.4394,  0.0040],
        [ 0.5186, -0.4379, -0.2009],
        [ 0.9509,  2.3721,  0.8443],
        [ 0.6170, -0.3416,  0.0879]])


In [17]:
# 索引操作
x=torch.randn(4,4)
print(x)
print(x[:,1]) #第一列
# 改变形状
x=x.view(16)
z=x.view(-1,8)
print(x.size(), y.size(), z.size())

tensor([[ 0.8346,  0.6249,  0.4447,  0.1674],
        [-0.6641,  1.2031,  0.8362, -1.3738],
        [-0.6558, -2.0685,  0.0553, -1.5611],
        [-1.4757,  0.9120, -0.3996,  0.2156]])
tensor([ 0.6249,  1.2031, -2.0685,  0.9120])
torch.Size([16]) torch.Size([5, 3]) torch.Size([2, 8])


In [18]:
# 如果是仅包含一个元素的 tensor，可以使用 .item（） 来得到对应的 python 数值
x=torch.randn(1)
print(x)
print(x.item())

tensor([0.0664])
0.06638932228088379


In [19]:
# torch->numpy
a=torch.ones(5)
print(a)
b=a.numpy()
print(b)
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [23]:
# numpy->torch
# CPU上的所有张量（ CharTensor 除外）都支持与 Numpy 的相互转换
a=np.ones(5)
b=torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [25]:
# 当GPU可用时,我们可以运行以下代码
# 我们将使用`torch.device`来将tensor移入和移出GPU
if torch.cuda.is_available():
    device=torch.device("cuda")
    y = torch.ones_like(x, device=device)  # 直接在GPU上创建tensor
    x=x.to(device)
    z=x+y
    print(z)

tensor([1.0664], device='cuda:0')


In [28]:
# 创建一个张量并设置requires_grad=True用来追踪其计算历史
x=torch.ones(2,2,requires_grad=True)
print(x)
y=x+2
print(y)
# y是计算的结果，所以它有grad_fn属性
print(y.grad_fn)

z=y*y*3
out=z.mean()
print(z,out)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [3]:
# .requires_grad_(...) 原地改变了现有张量的 requires_grad 标志。
# 如果没有指定的话，默认输入的这个标志是False。
a=torch.randn(2,2)
a=((a*3)/(a-1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [5]:
# 雅可比向量积的例子
x=torch.randn(3,requires_grad=True)
y=x*2
while y.data.norm() < 1000:
    y=y*2
print(y)

# 在这种情况下，y不再是标量。torch.autograd不能直接计算完整的雅可比矩阵
# 只想要雅可比向量积，只需将这个向量作为参数传给backward
v=torch.tensor([0.1,1.0,0.0001],dtype=torch.float)
y.backward(v)
print(x.grad)

tensor([ 611.9094,  856.8845, -799.6572], grad_fn=<MulBackward0>)
tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [6]:
# 为了防止跟踪历史记录（和使用内存），可以将代码块包装在with torch.no_grad():中
# 在评估模型时特别有用
# 来阻止autograd跟踪
print(x.requires_grad)
print((x ** 2).requires_grad)
with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


In [4]:
# nn包则依赖于autograd包来定义模型并对它们求导。
# 一个nn.Module包含各个层和一个forward(input)方法，该方法返回output
class Net(nn.Module):
    def init(self):
        super(Net,self).init()
        # 输入图像channel：1；输出channel：6；5x5卷积核
        self.conv1=nn.Conv2d(1,6,5)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)
        # 2x2 Max pooling
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # 如果是方阵,则可以只使用一个数字进行定义
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x